spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug

jwt:
  token:
    jwt-secret-key: weqweqwqwt12345678wantedpreongasdf12314boardingjwtsecret12345678


---

spring:
  config.activate.on-profile: prod

---

spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
